const appColors = {
  primaryColor: "#38A176",
  onPrimaryColor: "#FFFFFF",
  primaryContainerColor: "#D7ECE3",
  onPrimaryContainerColor: "#16402F",
  secondaryColor: "#447E7E",
  onSecondaryColor: "#FFFFFF",
  secondaryContainerColor: "#DDECEC",
  onSecondaryContainerColor: "#192F2F",
  tertiaryColor: "#8A835C",
  onTetiaryColor: "#FFFFFF",
  tertiaryContainerColor: "#EFEDE3",
  onTertiaryContainerColor: "#343122",
  errorColor: "#BA1A1A",
  onErrorColor: "#FFFFFF",
  errorContainerColor: "#FFF1EF",
  onErrorContainerColor: "#410002",
  surfaceDimColor: "#E6E6E6",
  surfaceColor: "#F2F2F2",
  surfaceBright: "#FFFFFF",
  surfaceContainerLowest: "#FFFFFF",
  surfaceContainerLow: "#F2F2F2",
  surfaceContainer: "#E6E6E6",
  surfaceContainerHight: "##D9D9D9",
  surfaceContainerHighest: "#CCCCCC",
  onSurface: "#1A1C18",
  onSurfaceVariant: "#333333",
  outline: "#999999",
  outlineVariant: "#B3B3B3",
};

export default appColors;
